from __future__ import annotations

"""Aliases dùng để nhận diện chỉ số và biến công thức từ text người dùng."""

BIOMARKER_ALIASES: dict[str, list[str]] = {
    "protein_niệu_24h": ["protein niệu", "protein nieu", "đạm niệu", "dam nieu", "protein niệu 24h"],
    "protein_mau": ["protein máu", "protein mau", "protein huyết", "protein huyet"],
    "albumin_máu": ["albumin máu", "albumin mau", "albumin huyết", "albumin huyet"],
    "cholesterol": ["cholesterol"],
    "ACR": [
        "acr",
        "albumin/creatinine",
        "albumin/creatinin",
        "albumin creatinine ratio",
        "tỷ lệ albumin/creatinine",
        "ty le albumin/creatinine",
        "tỷ lệ albumin/creatinin",
        "ty le albumin/creatinin",
    ],
    "PCR": [
        "pcr",
        "protein/creatinine",
        "protein/creatinin",
        "tỷ lệ protein/creatinine",
        "ty le protein/creatinine",
        "tỷ lệ protein/creatinin",
        "ty le protein/creatinin",
    ],
    "creatinine": ["creatinine", "creatinin"],
    "GFR": ["gfr", "egfr", "mức lọc cầu thận", "muc loc cau than", "mlct"],
    "BSA": ["bsa", "diện tích da", "dien tich da"],
    "FENa": ["fena", "fractional excretion of sodium"],
    "sodium": ["natri", "na", "na+", "sodium"],
    "urea": ["ure", "urea", "ure máu", "ure mau"],
    "hemoglobin": ["hb", "hemoglobin", "huyết sắc tố", "huyet sac to"],
    "hematocrit": ["hct", "hematocrit", "dung tích hồng cầu", "dung tich hong cau"],
    "pH": ["ph", "pH"],
    "bicarbonate": ["bicarbonat", "bicarbonate", "hco3", "hco3-"],
    "HbA1c": ["hba1c", "hba1c", "glycated hemoglobin"],
    "LDL_cholesterol": ["ldl", "ldl cholesterol"],
    "systolic_bp": ["huyết áp tâm thu", "huyet ap tam thu", "sys", "systolic", "sbp"],
    "diastolic_bp": ["huyết áp tâm trương", "huyet ap tam truong", "dia", "diastolic", "dbp"],
    "phosphorus": ["phospho", "phosphorus", "p máu", "p mau", "phosphate"],
    "creatinine_umol_l": ["creatinin umol", "creatinine umol", "creatinin μmol", "creatinine μmol"],
    "creatinine_change_umol_l": ["tăng creatinin", "tang creatinin", "creatinine rise", "creatinin tăng"],
    "potassium": ["kali", "k+", "potassium"],
}

FORMULA_VARIABLE_ALIASES: dict[str, list[str]] = {
    "age": ["tuổi", "tuoi", "age"],
    "weight_kg": ["cân nặng", "can nang", "weight", "weight_kg", "kg"],
    "height_cm": ["chiều cao", "chieu cao", "height", "height_cm", "cm"],
    "creatinine_mg_dl": ["creatinine", "creatinin", "creatinine_mg_dl"],
    "urine_na": ["urine_na", "una", "na niệu", "na nieu", "natri niệu", "natri nieu"],
    "plasma_na": ["plasma_na", "pna", "na máu", "na mau", "natri máu", "natri mau"],
    "urine_creatinine": ["urine_creatinine", "ucr", "creatinin niệu", "creatinin nieu"],
    "plasma_creatinine": ["plasma_creatinine", "pcr", "creatinin máu", "creatinin mau"],
    "sex": ["sex", "giới", "gioi", "giới tính", "gioi tinh"],
    "race": ["race", "chủng tộc", "chung toc"],
}

UNIT_ALIASES: dict[str, str] = {
    "g/24 giờ": "g/24h",
    "g/24h": "g/24h",
    "g/l": "g/L",
    "g/L": "g/L",
    "g/dl": "g/dL",
    "g/dL": "g/dL",
    "mmol/l": "mmol/L",
    "mmol/L": "mmol/L",
    "mg/g": "mg/g",
    "mg/mmol": "mg/mmol",
    "mg/dl": "mg/dL",
    "mg/dL": "mg/dL",
    "μmol/l": "μmol/L",
    "µmol/l": "μmol/L",
    "umol/l": "μmol/L",
    "μmol/L": "μmol/L",
    "mmhg": "mmHg",
    "mmHg": "mmHg",
    "ml/phút/1.73m2": "ml/ph/1.73m2",
    "ml/phút/1,73m2": "ml/ph/1.73m2",
    "ml/ph/1.73m2": "ml/ph/1.73m2",
    "ml/ph/1,73m2": "ml/ph/1.73m2",
    "ml/phút": "ml/ph",
    "ml/ph": "ml/ph",
    "kg": "kg",
    "cm": "cm",
    "%": "%",
}

FORMULA_OUTPUT_TO_BIOMARKER = {
    "gfr_ml_min_1_73m2": "GFR",
    "creatinine_clearance_ml_min": "creatinine_clearance",
    "bsa_m2": "BSA",
    "fena_percent": "FENa",
}
