from __future__ import annotations

from pathlib import Path


DEFAULT_CONTRACT_PATH = Path(__file__).resolve().parents[2] / "tool_contracts" / "medical_tools_contract.md"
ALLOWED_ENDPOINTS = {"/mcp/medical-tools/evaluate"}
ALLOWED_SECTION_TYPES = {
    "definition",
    "classification",
    "clinical_features",
    "diagnosis_criteria",
    "pathology",
    "treatment",
    "progression",
    "complications",
    "follow_up",
    "general",
}
ALLOWED_SOURCE_TYPES = {"chunk", "threshold", "formula"}
ALLOWED_DISEASE_NAMES = {
    "benh_than_man",
    "lupus_nephritis",
    "acute_kidney_injury",
    "hoi_chung_than_hu",
    "benh_than_iga",
    "diabetic_kidney_disease",
    "benh_ly_cau_than",
    "viem_cau_than_cap",
    "viem_cau_than_man",
}
DISEASE_NAME_ALIASES = {
    "lupus": "lupus_nephritis",
    "lupus_ban_do": "lupus_nephritis",
    "lupus ban do": "lupus_nephritis",
    "lupus_ban_đỏ": "lupus_nephritis",
    "lupus ban đỏ": "lupus_nephritis",
    "systemic_lupus_erythematosus": "lupus_nephritis",
    "systemic lupus erythematosus": "lupus_nephritis",
    "sle": "lupus_nephritis",
    "benh_than_lupus": "lupus_nephritis",
    "benh than lupus": "lupus_nephritis",
    "viem_than_lupus": "lupus_nephritis",
    "viem than lupus": "lupus_nephritis",
    "viem_cau_than_lupus": "lupus_nephritis",
    "viem cau than lupus": "lupus_nephritis",
    "nephrite_lupique": "lupus_nephritis",
    "benh_than_man_tinh": "benh_than_man",
    "benh than man tinh": "benh_than_man",
    "ckd": "benh_than_man",
    "chronic_kidney_disease": "benh_than_man",
    "chronic kidney disease": "benh_than_man",
    "suy_than_man": "benh_than_man",
    "suy than man": "benh_than_man",
    "aki": "acute_kidney_injury",
    "acute_kidney_injury": "acute_kidney_injury",
    "acute kidney injury": "acute_kidney_injury",
    "suy_than_cap": "acute_kidney_injury",
    "suy than cap": "acute_kidney_injury",
    "ton_thuong_than_cap": "acute_kidney_injury",
    "ton thuong than cap": "acute_kidney_injury",
    "fena": "acute_kidney_injury",
    "rifle": "acute_kidney_injury",
    "hoi_chung_than_hu": "hoi_chung_than_hu",
    "hoi chung than hu": "hoi_chung_than_hu",
    "than_hu": "hoi_chung_than_hu",
    "than hu": "hoi_chung_than_hu",
    "nephrotic_syndrome": "hoi_chung_than_hu",
    "nephrotic syndrome": "hoi_chung_than_hu",
    "benh_than_iga": "benh_than_iga",
    "benh than iga": "benh_than_iga",
    "viem_cau_than_iga": "benh_than_iga",
    "viem cau than iga": "benh_than_iga",
    "berger": "benh_than_iga",
    "viem_cau_than_cap": "viem_cau_than_cap",
    "viem cau than cap": "viem_cau_than_cap",
    "cap_sau_nhiem_lien_cau": "viem_cau_than_cap",
    "cap sau nhiem lien cau": "viem_cau_than_cap",
    "psagn": "viem_cau_than_cap",
    "dai_thao_duong": "diabetic_kidney_disease",
    "dai thao duong": "diabetic_kidney_disease",
    "than_dai_thao_duong": "diabetic_kidney_disease",
    "than dai thao duong": "diabetic_kidney_disease",
    "diabetic_kidney_disease": "diabetic_kidney_disease",
    "diabetic kidney disease": "diabetic_kidney_disease",
    "benh_ly_cau_than": "benh_ly_cau_than",
    "benh ly cau than": "benh_ly_cau_than",
    "benh_cau_than": "benh_ly_cau_than",
    "benh cau than": "benh_ly_cau_than",
    "viem_cau_than_man": "viem_cau_than_man",
    "viem cau than man": "viem_cau_than_man",
    "viem_cau_than_mang": "viem_cau_than_man",
    "viem cau than mang": "viem_cau_than_man",
    "mang_tang_sinh": "viem_cau_than_man",
    "mang tang sinh": "viem_cau_than_man",
}
LABEL_TRANSLATIONS = {
    "prerenal_aki_suggestive": "gợi ý suy thận cấp trước thận",
    "intrinsic_aki_suggestive": "gợi ý suy thận cấp tại thận",
    "anemia_threshold": "ngưỡng thiếu máu",
    "anemia_threshold_female": "ngưỡng thiếu máu ở nữ",
    "hematocrit_low": "hematocrit thấp",
    "blood_pressure_target": "mục tiêu huyết áp",
    "severe_hyperkalemia": "tăng kali máu nặng",
}
